//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagementLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBill
    {
        public int EmployeeID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public int TotalAmount { get; set; }
    
        public virtual tblRoute tblRoute { get; set; }
    }
}
